parameters:
  - name: RUN_WINDOWS
    type: boolean
    default: true
  - name: RUN_TEST_AND_RELEASE
    type: boolean
    default: true
  - name: OfficialBuild
    type: boolean

stages:
- stage: prep
  jobs:
  - job: SetVars
    displayName: Set Variables
    pool:
      type: linux

    variables:
      - name: ob_outputDirectory
        value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/BuildJson'
      - name: ob_sdl_codeSignValidation_enabled
        value: false
      - name: ob_sdl_codeql_compiled_enabled
        value: false
      - name: ob_sdl_credscan_suppressionsFile
        value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json
      - name: ob_sdl_tsa_configFile
        value: $(Build.SourcesDirectory)\PowerShell\.config\tsaoptions.json
      - name: ob_signing_setup_enabled
        value: false
      - name: ob_sdl_sbom_enabled
        value: false

    steps:
    - checkout: self
      clean: true
      env:
        ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

    - pwsh: |
        Get-ChildItem Env: | Out-String -width 9999 -Stream | write-Verbose -Verbose
      displayName: Capture environment variables
      env:
        ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

    - template: /.pipelines/templates/SetVersionVariables.yml@self
      parameters:
        ReleaseTagVar: $(ReleaseTagVar)
        CreateJson: yes

- stage: macos
  displayName: macOS - build and sign
  dependsOn: ['prep']
  variables:
    - name: ps_official_build
      value: ${{ parameters.OfficialBuild }}
  jobs:
  - template: /.pipelines/templates/mac.yml@self
    parameters:
      buildArchitecture: x64
  - template: /.pipelines/templates/mac.yml@self
    parameters:
      buildArchitecture: arm64

- stage: linux
  displayName: linux - build and sign
  dependsOn: ['prep']
  variables:
    - name: ps_official_build
      value: ${{ parameters.OfficialBuild }}
  jobs:
  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'linux-x64'
      JobName: 'linux_x64'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'linux-x64'
      JobName: 'linux_x64_minSize'
      BuildConfiguration: 'minSize'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'linux-arm'
      JobName: 'linux_arm'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'linux-arm64'
      JobName: 'linux_arm64'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'fxdependent-linux-x64'
      JobName: 'linux_fxd_x64_mariner'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'fxdependent-linux-arm64'
      JobName: 'linux_fxd_arm64_mariner'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'fxdependent-noopt-linux-musl-x64'
      JobName: 'linux_fxd_x64_alpine'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'fxdependent'
      JobName: 'linux_fxd'

  - template: /.pipelines/templates/linux.yml@self
    parameters:
      Runtime: 'linux-musl-x64'
      JobName: 'linux_x64_alpine'

- stage: windows
  displayName: windows - build and sign
  dependsOn: ['prep']
  condition: and(succeeded(),eq('${{ parameters.RUN_WINDOWS }}','true'))
  variables:
    - name: ps_official_build
      value: ${{ parameters.OfficialBuild }}
  jobs:
  - template: /.pipelines/templates/windows-hosted-build.yml@self
    parameters:
      Architecture: x64
      BuildConfiguration: release
      JobName: build_windows_x64_release
  - template: /.pipelines/templates/windows-hosted-build.yml@self
    parameters:
      Architecture: x64
      BuildConfiguration: minSize
      JobName: build_windows_x64_minSize_release
  - template: /.pipelines/templates/windows-hosted-build.yml@self
    parameters:
      Architecture: x86
      JobName: build_windows_x86_release
  - template: /.pipelines/templates/windows-hosted-build.yml@self
    parameters:
      Architecture: arm64
      JobName: build_windows_arm64_release
  - template: /.pipelines/templates/windows-hosted-build.yml@self
    parameters:
      Architecture: fxdependent
      JobName: build_windows_fxdependent_release
  - template: /.pipelines/templates/windows-hosted-build.yml@self
    parameters:
      Architecture: fxdependentWinDesktop
      JobName: build_windows_fxdependentWinDesktop_release

- stage: test_and_release_artifacts
  displayName: Test and Release Artifacts
  dependsOn: ['prep']
  condition: and(succeeded(),eq('${{ parameters.RUN_TEST_AND_RELEASE }}','true'))
  jobs:
  - template: /.pipelines/templates/testartifacts.yml@self

  - job: release_json
    displayName: Create and Upload release.json
    pool:
      type: windows
    variables:
    - name: ob_outputDirectory
      value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
    - name: ob_sdl_tsa_configFile
      value: $(Build.SourcesDirectory)\PowerShell\.config\tsaoptions.json
    - name: ob_sdl_credscan_suppressionsFile
      value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json
    steps:
    - checkout: self
      clean: true
    - template: /.pipelines/templates/SetVersionVariables.yml@self
      parameters:
        ReleaseTagVar: $(ReleaseTagVar)
    - template: /.pipelines/templates/rebuild-branch-check.yml@self
    - powershell: |
        $metadata = Get-Content '$(Build.SourcesDirectory)/PowerShell/tools/metadata.json' -Raw | ConvertFrom-Json

        # Use the rebuild branch check from the template
        $isRebuildBranch = '$(RebuildBranchCheck.IsRebuildBranch)' -eq 'true'

        # Don't mark as LTS release for rebuild branches
        $LTS = $metadata.LTSRelease.Package -and -not $isRebuildBranch

        if ($isRebuildBranch) {
          Write-Verbose -Message "Rebuild branch detected, not marking as LTS release" -Verbose
        }

        @{ ReleaseVersion = "$(Version)"; LTSRelease = $LTS } | ConvertTo-Json | Out-File "$(Build.StagingDirectory)\release.json"
        Get-Content "$(Build.StagingDirectory)\release.json"

        if (-not (Test-Path "$(ob_outputDirectory)\metadata")) {
          New-Item -ItemType Directory -Path "$(ob_outputDirectory)\metadata"
        }

        Copy-Item -Path "$(Build.StagingDirectory)\release.json" -Destination "$(ob_outputDirectory)\metadata" -Force
      displayName: Create and upload release.json file to build artifact
      retryCountOnTaskFailure: 2
    - template: /.pipelines/templates/step/finalize.yml@self
