parameters:
  - name: OfficialBuild
    type: boolean

stages:
- stage: prep
  displayName: 'Prep BuildInfo+Az'
  jobs:
  - template: /.pipelines/templates/checkAzureContainer.yml@self

- stage: mac_package
  displayName: 'macOS Pkg+Sign'
  dependsOn: []
  jobs:
  - template: /.pipelines/templates/mac-package-build.yml@self
    parameters:
      buildArchitecture: x64

  - template: /.pipelines/templates/mac-package-build.yml@self
    parameters:
      buildArchitecture: arm64

- stage: windows_package_build
  displayName: 'Win Pkg (unsigned)'
  dependsOn: []
  jobs:
  - template: /.pipelines/templates/packaging/windows/package.yml@self
    parameters:
      runtime: x64

  - template: /.pipelines/templates/packaging/windows/package.yml@self
    parameters:
      runtime: arm64

  - template: /.pipelines/templates/packaging/windows/package.yml@self
    parameters:
      runtime: x86

  - template: /.pipelines/templates/packaging/windows/package.yml@self
    parameters:
      runtime: fxdependent

  - template: /.pipelines/templates/packaging/windows/package.yml@self
    parameters:
      runtime: fxdependentWinDesktop

  - template: /.pipelines/templates/packaging/windows/package.yml@self
    parameters:
      runtime: minsize

- stage: windows_package_sign
  displayName: 'Win Pkg Sign'
  dependsOn: [windows_package_build]
  jobs:
  - template: /.pipelines/templates/packaging/windows/sign.yml@self
    parameters:
      runtime: x64

  - template: /.pipelines/templates/packaging/windows/sign.yml@self
    parameters:
      runtime: arm64

  - template: /.pipelines/templates/packaging/windows/sign.yml@self
    parameters:
      runtime: x86

  - template: /.pipelines/templates/packaging/windows/sign.yml@self
    parameters:
      runtime: fxdependent

  - template: /.pipelines/templates/packaging/windows/sign.yml@self
    parameters:
      runtime: fxdependentWinDesktop

  - template: /.pipelines/templates/packaging/windows/sign.yml@self
    parameters:
      runtime: minsize

- stage: linux_package
  displayName: 'Linux Pkg+Sign'
  dependsOn: []
  jobs:
  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_x64'
      signedDrop: 'drop_linux_sign_linux_x64'
      packageType: deb
      jobName: deb

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_fxd_x64_mariner'
      signedDrop: 'drop_linux_sign_linux_fxd_x64_mariner'
      packageType: rpm-fxdependent  #mariner-x64
      jobName: mariner_x64
      signingProfile: 'CP-459159-pgpdetached'

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_fxd_arm64_mariner'
      signedDrop: 'drop_linux_sign_linux_fxd_arm64_mariner'
      packageType: rpm-fxdependent-arm64 #mariner-arm64
      jobName: mariner_arm64
      signingProfile: 'CP-459159-pgpdetached'

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_x64'
      signedDrop: 'drop_linux_sign_linux_x64'
      packageType: rpm
      jobName: rpm

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_arm'
      signedDrop: 'drop_linux_sign_linux_arm'
      packageType: tar-arm
      jobName: tar_arm

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_arm64'
      signedDrop: 'drop_linux_sign_linux_arm64'
      packageType: tar-arm64
      jobName: tar_arm64

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_x64_alpine'
      signedDrop: 'drop_linux_sign_linux_x64_alpine'
      packageType: tar-alpine
      jobName: tar_alpine

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_fxd'
      signedDrop: 'drop_linux_sign_linux_fxd'
      packageType: fxdependent
      jobName: fxdependent

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_x64'
      signedDrop: 'drop_linux_sign_linux_x64'
      packageType: tar
      jobName: tar

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_fxd_x64_alpine'
      signedDrop: 'drop_linux_sign_linux_fxd_x64_alpine'
      packageType: tar-alpine-fxdependent
      jobName: tar_alpine_fxd

  - template: /.pipelines/templates/linux-package-build.yml@self
    parameters:
      unsignedDrop: 'drop_linux_build_linux_x64_minSize'
      signedDrop: 'drop_linux_sign_linux_x64_minSize'
      packageType: min-size
      jobName: minSize

- stage: nupkg
  displayName: 'NuGet Pkg+Sign'
  dependsOn: []
  jobs:
  - template: /.pipelines/templates/nupkg.yml@self

- stage: msixbundle
  displayName: 'MSIX Bundle+Sign'
  dependsOn: [windows_package_build]  # Only depends on unsigned packages
  jobs:
  - template: /.pipelines/templates/package-create-msix.yml@self
    parameters:
      OfficialBuild: ${{ parameters.OfficialBuild }}

- stage: upload
  displayName: 'Upload'
  dependsOn: [prep, mac_package, windows_package_sign, linux_package, nupkg, msixbundle]  # prep needed for BuildInfo JSON
  jobs:
  - template: /.pipelines/templates/uploadToAzure.yml@self

- stage: validatePackages
  displayName: 'Validate Packages'
  dependsOn: [upload]
  jobs:
  - template: /.pipelines/templates/release-validate-packagenames.yml@self
